---
version: 0.2

phases:
  install:
    commands:
    - npm install -g bespoken-tools
  pre_build:
    commands:
    - cd lambda/custom; npm install
  build:
    commands:
    - cd $CODEBUILD_SRC_DIR
    - bst test
    - cd lambda/custom; npm test

